### ISSUE TITLE
Empty project shows NaN values in "Tasks summary"

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#10]
While minor issue at this point, when I add a new project without any tasks, it shows NaN% for Idle, In progress, Completed, Start today, Overdue.

**Comment by synapse** [comment]
@jiuweigui this should be fixed in [Beta 7](https://getstacksapp.com/updates/#version-1.0.0-beta-7)

**Comment by jiuweigui** [comment]
Tested with 1.0.0 Beta 9 => OK
