### ISSUE TITLE
Adding bookmarks doesn't show anything except empty space in "Bookmarks"

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#11]
When I add projects as bookmarks through quick add and then try to access them through "Bookmarks" it shows "bookmarks.type-undefined" on the top and entry that does not show any text and the entry does not lead anywhere when clicked.

**Comment by synapse** [comment]
@jiuweigui should be fixed in [Beta 13](https://github.com/stacks-task-manager/stacks2/releases/tag/v1.0.0-beta13)

**Comment by jiuweigui** [comment]
Tested with 1.0.0-beta13 => OK.
