### ISSUE TITLE
New note has null as content

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#12]
Minor thing but when you create a new note it already contains "null"... then again Stacks1 had "undefined" as header and lorem ipsum as content so I'm not sure if this is improvement or not compared to that.

**Comment by synapse** [comment]
@DAmNRelentless should be fixed in [Beta 8](https://getstacksapp.com/updates/#version-1.0.0-beta-8)

**Comment by jiuweigui** [comment]
Tested with  1.0.0 Beta 9 => OK
