### ISSUE TITLE
Automation menu doesn't work with dark mode

### ISSUE THREAD

**Issue by DAmNRelentless** [stacks-task-manager/stacks2#13]
When in dark mode, the automation menu is almost unusable because you can't see a lot.

https://user-images.githubusercontent.com/16513358/214867329-7678e60d-a3b3-450a-af65-7ce52814a7c9.mp4

**Comment by synapse** [comment]
@DAmNRelentless this should be fixed in [Beta 7](https://getstacksapp.com/updates/#version-1.0.0-beta-7)
