### ISSUE TITLE
Notepad cursor is not aligned

### ISSUE THREAD

**Issue by DAmNRelentless** [stacks-task-manager/stacks2#15]
Besides the bug mentioned in https://github.com/stacks-task-manager/stacks2/issues/12, the cursor of the notepad doesn't seem to be aligned correctly.

When removing the null string, you can see placeholder text which starts from a completely different position than your cursor.

https://user-images.githubusercontent.com/16513358/215064245-7fd91bbd-d58f-4b8f-9111-fe32b58f1b82.mp4

**Comment by synapse** [comment]
@DAmNRelentless should be fixed in [Beta 8](https://getstacksapp.com/updates/#version-1.0.0-beta-8)
