### ISSUE TITLE
Selecting Help from the top bar is (empty)

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#16]
Using 1.0.0 Beta 9, when I select "Help" from the top bar it only shows (empty). However the "Help" form the left sidebar shows other selections.

**Comment by synapse** [comment]
Hey @jiuweigui is this on Windows/Linux?

**Comment by jiuweigui** [comment]
This is on Windows 11.

**Comment by synapse** [comment]
@jiuweigui should be fixed in [Beta 13](https://github.com/stacks-task-manager/stacks2/releases/tag/v1.0.0-beta13)
