### ISSUE TITLE
Deleting bookmarked project does not delete the bookmark

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#18]
Win11, 1.0.0-beta13

Steps:
1. Create project
2. Bookmark project
3. Delete bookmarked project
4. Bookmark still exists, clicking it results in "project not found" pop-up.

**Comment by synapse** [comment]
@jiuweigui this should be fixed in Beta 15

**Comment by jiuweigui** [comment]
Tested with 1.0.0-beta15 => OK.

**Comment by jiuweigui** [comment]
When I restart Stacks2 1.0.0-beta15, deleted bookmarks are repopulated again and again (i.e. If I delete bookmarks again by hand and restart app they're still in the bookmarks).

**Comment by synapse** [comment]
@jiuweigui is this still an issue with the latest version?

**Comment by jiuweigui** [comment]
This seems to be fixed in beta18.
