### ISSUE TITLE
Feature request: Add "About" to "Help"

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#19]
Currently preferences is the only place I've found where you can see the version. It would be logical that this is available also through the "Help" as that's where most applications put the version information anyway so that it's easily accessible.

**Comment by synapse** [comment]
@jiuweigui  this should be fixed in Beta 15

**Comment by jiuweigui** [comment]
Tested with 1.0.0-beta15 => OK.
