### ISSUE TITLE
Creating and deleting project with tasks shows them in new project created

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#20]
Win11 1.0.0-beta13
Steps:
1. Create a project
2. Create new stack (like todo)
3. Create few tasks under the created stack
4. Delete the project
5. Create new project (with completely different name for example)
6. Select new project and then change from "Board" to "List" -> You'll see the tasks from the deleted project.

**Comment by jiuweigui** [comment]
To add to this, there's something funny happening with the views or that I misunderstand them.

For example if I add two projects where I add stack and tasks for the first one, I can see them still when I select "List"-view on the second stack I did not add anything. Are these views global or project-based?

**Comment by synapse** [comment]
Hey @jiuweigui thanks for this my bad, I've forgot to re-enable a filter and it does not clear the loaded tasks when switching projects.

**Comment by synapse** [comment]
@jiuweigui this should be fixed in Beta 14

**Comment by jiuweigui** [comment]
Tested with 1.0.0-beta15 => OK.
