### ISSUE TITLE
"Jump to" won't actually remove deleted references to files when "Remove file" is selected

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#21]
Win11 1.0.0-beta13

Steps:
1. Add file attachment
2. Select the file attachment (no need to open it, just make sure it appears to "Jump to")
3. Delete the file attachment through the file attachment view (where you can open it)
4. Select "Jump to" and the deleted file attachment
5. Select "Remove file" from the prompt
6. Go back to "Jump to", reference still exists despite selecting removal

**Comment by synapse** [comment]
@jiuweigui this should be fixed in Beta 15

**Comment by jiuweigui** [comment]
I can still reproduce this with 1.0.0-beta15.

**Comment by synapse** [comment]
@jiuweigui if the jump menu was previously populated it won't delete it. It has to have the newly added id correct in there.
Could you maybe upload a quick video of what you see when deleting the project?

**Comment by jiuweigui** [comment]
![output](https://user-images.githubusercontent.com/3492980/216772973-1c834735-7931-495e-b867-ad8dc7ec272c.gif)

**Comment by synapse** [comment]
@jiuweigui is this still an issue with the latest version?

**Comment by jiuweigui** [comment]
This seems to be fixed in beta18.
