### ISSUE TITLE
Project "Overview" updates task statuses very slow

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#22]
Win11 1.0.0-beta13

Steps:
1. Create project and add stack and tasks to it (1+)
2. Change to "Overview", it takes ~1s per task to become visible on the "Tasks summary"-box

**Comment by synapse** [comment]
Hey @jiuweigui could you attach a quick screen recording? I've tried on a board with +100 tasks and 12 stacks and it's all snappy

**Comment by jiuweigui** [comment]
https://user-images.githubusercontent.com/3492980/216462370-d430770d-e97e-4739-a453-9791b8e842dc.mp4

**Comment by synapse** [comment]
Ah, not I understand, you mean the  counter animation? Yeah that's not a problem. It won't take 1 second for each task you'll have.
