### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by civic9** [stacks-task-manager/stacks2#23]
OS: Linux (Arch). 
Beta 16, 17, 18.

Just after start I can only see: Application crashed.
Red alert with a message: "The feature watch recursively is unavailable on the current platform, which is being used to run Node.js".

**Comment by synapse** [comment]
Hey @civic9 does this happen with a specific workspace? If yes would you mind sharing it? There's seams to be a problem with the `documents.tree` file which either it was tempered with or something wasn't read correctly.

**Comment by civic9** [comment]
Btw, if I delete only workspace directory (leaving ~/.config/Stack 2" intact) next time the app recreates the directory and there are many more files. But when starting next time again the same error.

**Comment by synapse** [comment]
@civic9 I can't seem to replicate this issue. I've tried both from an empty folder (when adding a new workspace) and loading the default one.
I'll keep investigating.

**Comment by civic9** [comment]
@synapse 
I didn't check beta19 and beta20, but this problem doesn't exist in beta21 :)
