### ISSUE TITLE
Unable to enter any text in "Private Notes" 

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#24]
Win11 1.0.0-beta21:

I am unable to add any text in the "Private Notes" box on the Home-page. Only thing I can add is from the "Insert"-button (for example callouts, table) but I'm unable to do or edit them in any way.

**Comment by synapse** [comment]
@jiuweigui when the app releases ping me in Slack, I have a license for you ☺️😉

**Comment by jiuweigui** [comment]
Tested with beta24 => OK.

Thanks. I really appreciate it. Been using the first one with license quite some time now. Unfortunately I don't have/use slack.
