### ISSUE TITLE
Feature: Todos dont have any ordering except insert order in "Home"-view

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#26]
Win11 beta21:

When adding new todo items from home-view they are shown on the list in the order of insert. Assigning due-date doesn't change anything which makes it hard to understand from user perspective what is a priority and what is not without having to go through the complete list.

Todos should be ordered by either ASC or DESC based on set due date and putting todos without dates either top or bottom. This would allow the user to see them at least in some logical order.

**Comment by synapse** [comment]
@jiuweigui this should be fixed

**Comment by jiuweigui** [comment]
Tested with beta24 => OK.
