### ISSUE TITLE
Bookmarking and pinning user (people) creates unusable reference to Home-view

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#27]
Win11 beta21:

When I create a new user, bookmark and pin the bookmark it becomes visible on the Home-view "pinned bookmarks"-section but pressing it does nothing. It does not open the user information when clicked or do anything that would be expected clicking it to do.

**Comment by synapse** [comment]
@jiuweigui this should be fixed

**Comment by jiuweigui** [comment]
Tested with beta24 => OK.
