### ISSUE TITLE
Using "add to favorities" in People does not seem to do anything

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#28]
Win11 beta21:

When I try to use "add to favorities" in People (same place where export is), it does not do anything. It does not become visible in anywhere I could find. Not in the left area (under "General") nor in the "home"-view or anywhere else.

**Comment by synapse** [comment]
@jiuweigui this should be fixed

**Comment by jiuweigui** [comment]
Tested with beta24 => OK.
