### ISSUE TITLE
Filtering People based on type does not work

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#31]
Win11 beta21:

When I add 2 people entries with different types (for example Standard and Client) and then attempt to filter using "Standard" (and pressing refresh people) the shown list is completely empty even though it should contain one user. Same thing happens when I attempt to filter using "Client".

Only when using filter "All Types" I can see users on the list.

Company filter on the other hand seems to be working as expected.

**Comment by synapse** [comment]
@jiuweigui this should be fixed

**Comment by jiuweigui** [comment]
Tested with beta24 => OK.
