### ISSUE TITLE
Searching people with non-existent values displays empty list that can't be reset

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#33]
Win11 beta21:

When I add few people entries and use "Search person" to search something that does not exist, the "Search person"-box is emptied and no hits are returned. As empty search box is not accepted (which would be expected to match everything) I haven't found how I can reset the search so that it would show all entries without restarting the application.

This should allow empty searches that matches and lists all entries. 

Added bonus would be to leave the search term in the box after search to show that filtering is being done in the first place as otherwise it's not apparent to the user.

**Comment by synapse** [comment]
@jiuweigui this should be fixed

**Comment by jiuweigui** [comment]
Tested with beta24 => OK.
