### ISSUE TITLE
People types in type-field and type-filter have different coloring

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#36]
Win11 beta24 with pre-generated people list:

For some reason there's difference in the type-field coloring and the All types filter for the same types. For example "Friend" type-field shows the color as purple but the all types filter shows it as green.

![image](https://user-images.githubusercontent.com/3492980/224183984-de3a4c21-1be1-45a4-bbbf-646d29c72c8a.png)

**Comment by synapse** [comment]
@jiuweigui this should be fixed in Beta 26

**Comment by jiuweigui** [comment]
Tested with beta27 => OK.
