### ISSUE TITLE
Creating double bookmark entries for bookmarked and pinned people

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#37]
Win11 beta24:

1. Select a demo user "Aaron Drake" and bookmark him but don't enable "Pinned". Press "Add bookmark" and go to "Bookmarks". You can see "Aaron Drake" in "People" (in the Bookmarks).
2. Select "Aaron Drake" from "People" and this time a pinned bookmark. There's now "Aaron Drake" both on "Pinned bookmarks" and "People" (in the Bookmarks).
3. Select "Aaron Drake" from "People" and "Add bookmark" - "Pinned" is enabled. Unselect "Pinned" and press "Add bookmark". After this there's 1 "Aaron Drake" in the "Pinned bookmarks" and 2 "Aaron Drake" in "People".

**Comment by synapse** [comment]
@jiuweigui this should be fixed in Beta 26
