### ISSUE TITLE
completed tasks automatically hidden

### ISSUE THREAD

**Issue by Cmhorn** [stacks-task-manager/stacks2#38]
When completing a task by the checkmark icon on the stacked task, or by the checkbox 'Done', The completed task disappears, and the message 'Completed task automatically hidden' is displayed. 

Is there a way to disable this automation? 

Is there a way to view completed tasks?

**Comment by synapse** [comment]
@Cmhorn tasks are hidden because the default filter is set to only shows incomplete tasks. To view completed tasks open the filters from the toolbar and set to view either all tasks or just the completed ones.

**Comment by synapse** [comment]
In the Preferences you have the option to disable automatically hiding the completed tasks:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/71137/226832157-7f2fa712-0dbd-46f8-bae3-9ace5df2be64.png">
