### ISSUE TITLE
Tasks become hidden when they are attached to an other task

### ISSUE THREAD

**Issue by lucafadigati** [stacks-task-manager/stacks2#39]
**Describe the bug**
When I attach a task B to an other task A, it becomes a subtask and it disappear from the project list.

**To Reproduce**
Create two task and attach the second to the first.

**Expected behavior**
The expected behavior is that the task B will be added at the subtask list of the task A, but the task B will still visible in the project.

**Desktop (please complete the following information):**
 - Ubuntu 20.04

**Comment by synapse** [comment]
Hey @lucafadigati this happens when a task becomes a subtask of another by attaching and you've not set to view subtasks on the board along side the parent tasks.

**Comment by lucafadigati** [comment]
I am sorry, I did not see the button to set this option. Now, I found it, thank you.
