### ISSUE TITLE
Overall view

### ISSUE THREAD

**Issue by lucafadigati** [stacks-task-manager/stacks2#40]
Good evening. I suggest to add the possibility to show multiple projects in the same Gantt view or Calendar view in order to have a complete overview of the all scheduled work commitments. So I suggest to add in the workspace a new section under the "Documents section", called Views, or Summary, where it is possible to create a combined view from different projects.

![Screenshot from 2023-03-18 19-18-50](https://user-images.githubusercontent.com/93828128/226126536-d6eabc63-1fd0-4dd5-adce-8a1ac15894a6.png)

**Comment by synapse** [comment]
Hey @lucafadigati, there's the `Reports` view in the sidebar which is a minimal overview of all projects. You can see there the same info as in the `Overview` view but in a table format to have a better way to compare results.
The reports should have a Gantt view letting you see and manage project's start and end dates.

The calendar is already showing all task across all projects. There will be a filter to let the user enable specific projects.
