### ISSUE TITLE
Gantt view dark theme

### ISSUE THREAD

**Issue by lucafadigati** [stacks-task-manager/stacks2#42]
The Gantt view is unreadable with the dark theme because the even lines have a background color that is equal to the text one.
![Screenshot from 2023-03-21 10-20-26](https://user-images.githubusercontent.com/93828128/226563740-cbfe6bd7-5397-417e-aa09-1ed379f5c936.png)

**Comment by synapse** [comment]
Hey @lucafadigati this should be fixed in the latest beta 29
