### ISSUE TITLE
No Keyboard Shortcut to Add New Stack

### ISSUE THREAD

**Issue by HobbesKo** [stacks-task-manager/stacks2#5]
With 'Hide New Stack Button' enabled in board view, there is no way to add a new stack. There appears to be no keyboard shortcut.

This may be related; the keyboard shortcut for adding new people or a new calendar event does not add anything.

Stacks 2 beta 4 on Windows 11.

**Comment by HobbesKo** [comment]
Nope, does not appear to be fixed.
What key combination should I be using on Windows to get a new Stack?

**Comment by synapse** [comment]
@HobbesKo should be "meta+shift+n"

**Comment by HobbesKo** [comment]
Sorry, pilot error. Just figured out what 'meta' means in this context.
I assumed it would be CTRL+Shift+N, but it's Windows+Shift+N  🙄. I must have tried every other obvious key combination going.

**Comment by HobbesKo** [comment]
Any chance it can be changed to CTRL+Shift+N? Seems a bit more intuitive.

**Comment by HobbesKo** [comment]
CTRL+Shift+N now works for adding a new stack.

Many thanks 👍
