### ISSUE TITLE
Backlog total not updating

### ISSUE THREAD

**Issue by Devilstorment** [stacks-task-manager/stacks2#51]
When I add items to my backlog in any project board, then delete them, the total at the top of the stack does not update.

I have compared with moving a task from "backlog" to "to do" and it updates. I have also tried deleting a task from "to do" or "doing" and it updates as expected. It seems to only be when deleting from the backlog.

**Comment by synapse** [comment]
Hey @Devilstorment this should be fixed since v2.5.0
