### ISSUE TITLE
Marking subtask done in Board view does not mark it done in the parent task

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#53]
Hi.

When subtasks are visible and I mark one as done in the Board, the stack-field gets updated but it is still shown to-do on the parent task. If I do everything from the parent task the status is updated as expected (i.e. if I mark it as done it's done also on board and if I mark it as to-do, it's marked as to-do on board).

Tested on Windows/v2.5.2

**Comment by synapse** [comment]
Hey @jiuweigui this should be fixed since [v2.5.4](https://getstacksapp.com/updates/#version-2.5.4)
