### ISSUE TITLE
Enhancement: visually separate stacks from each other

### ISSUE THREAD

**Issue by xdp0** [stacks-task-manager/stacks2#58]
Hi, I'd want an option to visually separate stacks from each other with the color or border, like it was in Stacks1.

**Comment by synapse** [comment]
Hey @xxddpp, in Stacks 2, the columns do not utilize any background color, but you have the option to add a tint color to each of them. If you prefer a more vibrant color, you can adjust the column tint preference to increase the intensity from the preferences.

![SCR-20240208-rp9](https://github.com/stacks-task-manager/stacks2/assets/71137/4a78cb75-97f6-4cc8-bce2-7752a1cce91f)

**Comment by xxddpp** [comment]
hi, yes I saw it and it's nice option; but the tasks below headers still look like there's no difference between them, all belonging to the same bulletin board.

I know that's subjective but maybe an option like permanent visible scrollbar on the right side of each list will help to visually separate lists from each other.

**Comment by synapse** [comment]
Hey @xdp0 version 2.6.0 introduces columns background which makes stacks more evident.
