### ISSUE TITLE
Empty window on 2.6 release

### ISSUE THREAD

**Issue by OopsPwnedUAgain** [stacks-task-manager/stacks2#59]
![image](https://github.com/user-attachments/assets/e7a7e152-9264-4e47-b43d-1a8e6fd87bfc)
![image](https://github.com/user-attachments/assets/030b2b74-7b9d-4323-948e-937c9316e93a)

Running this on a win10-ltsc-iot current install with all the current windows patches.  The program opens to a blank white background and none of the buttons seem to do anything except the developer tools.  I tried installing Node.js  separately but it doesn't seem to make a difference.

**Comment by synapse** [comment]
Hey @OopsPwnedUAgain Stacks seems to be working well in all of our tests both on Windows 10 and 11. I can see that you have an error in your console, would you mind sharing a screenshot of that as well?

**Comment by OopsPwnedUAgain** [comment]
Here's the view with that error expanded.  I don't understand why there's a
problem with S but not the other variables, strange.
[image: image.png]

**Comment by armaaar** [comment]
I get the same with Linux Ubuntu 22.04.4 LTS
![image](https://github.com/user-attachments/assets/31afc9da-1eac-441d-93c3-3dedffd84ed0)

**Comment by synapse** [comment]
Could you please check with the latest version: https://github.com/stacks-task-manager/stacks2/releases/tag/v2.6.1

**Comment by OopsPwnedUAgain** [comment]
Looking good on 2.6.1 for me.

**Comment by armaaar** [comment]
Works well for me as well. Thanks!
