### ISSUE TITLE
Remove stacks logo from exported PDF

### ISSUE THREAD

**Issue by fatrex** [stacks-task-manager/stacks2#63]
I think that stacks logo should be remove from exported PDF documents, or add an option to remove it (for registered subsribers maybe?)

I use stacks to create essays and documentation and everytime I need to export the documents for sharing i need to use another tool because of the logo.

![image](https://github.com/user-attachments/assets/653c1154-7ad7-48ae-99a4-73a97ea93841)

**Comment by synapse** [comment]
Hey @fatrex this should be fixed in [v2.6.6](https://github.com/stacks-task-manager/stacks2/releases/tag/v2.6.6)
