### ISSUE TITLE
code is not visible in notepad dark theme, no codeblock

### ISSUE THREAD

**Issue by DAmNRelentless** [stacks-task-manager/stacks2#7]
Code snippets are not visible when using the dark theme inside the notepad.
Light theme:
![](https://i.imgur.com/wOf3Wgb.png)
Dark theme:
![](https://i.imgur.com/2Pqlyzf.png)

Code blocks don't work at all.

**Comment by synapse** [comment]
Should be fixed in [Beta 5](https://getstacksapp.com/updates/#version-1.0.0-beta-5)

**Comment by DAmNRelentless** [comment]
> Code snippet color should be fixed in [Beta 5](https://getstacksapp.com/updates/#version-1.0.0-beta-5)

Yep, looks good.

Any plans to add codeblocks as well?

**Comment by synapse** [comment]
Should be there by next beta update

**Comment by synapse** [comment]
Should be fixed in [Beta 6](https://github.com/stacks-task-manager/stacks2/releases/tag/v1.0.0-b6)

**Comment by DAmNRelentless** [comment]
I seem not able to create a codeblock. What's the syntax? Same as here on GitHub? If so, it doesn't work. Also the code button does only create an in-line code snippet.

**Comment by synapse** [comment]
@DAmNRelentless  Try something like this:


https://user-images.githubusercontent.com/71137/214884986-afbc1948-e10f-4be0-b8f1-8f3577229728.mov

**Comment by DAmNRelentless** [comment]
Would it be possible to automatically convert the typical three backticks syntax to the codeblock as well?

Other than that, this looks fine. I didn't see that option in the dropdown.

**Comment by synapse** [comment]
@DAmNRelentless should already work like that.


https://user-images.githubusercontent.com/71137/215056097-81970d6c-c851-41b7-b28d-6dde54d61460.mov

**Comment by DAmNRelentless** [comment]
Oh, right. It seems to work after the triple backticks and pressing space. I am just used to hitting enter and this doesn't work. Might also be a bug?

**Comment by synapse** [comment]
Since it's not an actual markdown editor it only reacts and converts text from a markdown syntax when it starts with a markdown format character + space.

**Comment by DAmNRelentless** [comment]
Alright, that seems reasonable.
