### ISSUE TITLE
`Edit workspace` button does not work

### ISSUE THREAD

**Issue by DAmNRelentless** [stacks-task-manager/stacks2#8]
https://user-images.githubusercontent.com/16513358/214410040-f2fa0a34-cd9d-4ca6-98cb-695fbd49a66f.mp4

The button seems to do nothing so far.

**Comment by synapse** [comment]
Should be fixed in [Beta 6](https://github.com/stacks-task-manager/stacks2/releases/tag/v1.0.0-b6)

**Comment by DAmNRelentless** [comment]
Yep, thank you!
