### ISSUE TITLE
Accessing projects from "Favorite projects" on Home does not work

### ISSUE THREAD

**Issue by jiuweigui** [stacks-task-manager/stacks2#9]
When I add a project as favorite and try to access it from "Favorite projects" shows empty page and error "Project not found!".

**Comment by synapse** [comment]
@jiuweigui should be fixed in [Beta 8](https://getstacksapp.com/updates/#version-1.0.0-beta-8)

**Comment by jiuweigui** [comment]
Tested with  1.0.0 Beta 9 => OK.
